### PR TITLE
Fix issue6

### PR DESCRIPTION
**Pull request by alebyk113**
flag -f passed
flag --send added to send massmail

### CODE REVIEW

**Comment by keszybz** [comment]
Oh, one more comment: the title of the PR should be more descriptive. Issue number should be in a comment, and the title should be something that describes the change. For example:
```
Replace -f option with --send

Instead of -f to skip sending, --send must be passed to actually send anything.
Closes #6.
```
(The reason is that after a while nobody remembers issue numbers, so if you see a commit like "Fix issue6", you first need to go to github to see what issue6 was about.)

**Comment by jakobj** [comment]
Nice work, but I see two issues:
- `--send` is not parsed from the command line options properly; you need to add ` ['send']` as an option to `getopt.getopt`; @keszybz can you confirm this?
- tests fail, because you need to pass `--send` in `test_fake_sending()`

**Comment by keszybz** [comment]
...and one more thing: the tests fail. See https://travis-ci.org/ASPP/massmail/builds/269128908?utm_source=github_status&utm_medium=notification.

Try running
```pytest -v```

**Comment by alebyk113** [comment]
not sure can use pytest -v as still in python 2 ? Get errors for all except *, err: to be changed to except * as err:

**Pull request closed without merging**
